In [3]:
from sklearn.model_selection import train_test_split
from ast import literal_eval
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
import random
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import torch
import h5py
from torch.utils.data import DataLoader, TensorDataset, random_split

In [2]:
file_path = 'F:\ISEP_Learning_Document\Semester3\End-of-track Project\dataset\data_raw\GOLD_XYZ_OSC.0001_1024.hdf5'

In [4]:
# Open my file in read mode
file_raw = h5py.File(file_path,'r')

In [5]:
# access the datasets within the HDF5 File
data_raw_x = file_raw['X'][:]
data_raw_y = file_raw['Y'][:]
data_raw_z = file_raw['Z'][:]

In [6]:
# Convert the hdf5 dataset to a PyTorch tensor
X_tensor = torch.from_numpy(data_raw_x).float()
Y_tensor = torch.from_numpy(data_raw_y).long()
Z_tensor = torch.from_numpy(data_raw_z).long()

In [7]:
# The information about dataset X
print("Tensor Dataset_X Information:")
print("--------------------------")

# Check the data type of the tensor dataset
print(f"Data type: {X_tensor.type()}")

# Get the shape (dimensions) of the data
print(f"Data shape: {X_tensor.shape}")

# Check the number of elements in the dataset
print(f"Number of elements: {X_tensor.numel()}")

# Access the first few elements of the data
print("First few data elements:")
print(X_tensor[:2])

Tensor Dataset_X Information:
--------------------------
Data type: torch.FloatTensor
Data shape: torch.Size([2555904, 1024, 2])
Number of elements: 5234491392
First few data elements:
tensor([[[ 0.0420,  0.2348],
         [-0.2729,  0.4051],
         [-0.2671,  0.2275],
         ...,
         [-0.7056, -0.2869],
         [-0.4116,  0.6683],
         [ 0.0649,  0.6358]],

        [[ 1.1986,  0.4494],
         [ 0.4854,  0.2827],
         [ 0.8679, -0.3319],
         ...,
         [-1.2129, -0.6429],
         [-0.3810,  0.7936],
         [ 0.0864,  1.0922]]])


In [8]:
# The information about dataset Y
print("Tensor Dataset_Y Information:")
print("--------------------------")

# Check the data type of the tensor dataset
print(f"Data type: {Y_tensor.type()}")

# Get the shape (dimensions) of the data
print(f"Data shape: {Y_tensor.shape}")

# Check the number of elements in the dataset
print(f"Number of elements: {Y_tensor.numel()}")

# Access the first few elements of the data
print("First few data elements:")
print(Y_tensor[:2])

Tensor Dataset_Y Information:
--------------------------
Data type: torch.LongTensor
Data shape: torch.Size([2555904, 24])
Number of elements: 61341696
First few data elements:
tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])


In [9]:
# The information about dataset Z
print("Tensor Dataset_Z Information:")
print("--------------------------")

# Check the data type of the tensor dataset
print(f"Data type: {Z_tensor.type()}")

# Get the shape (dimensions) of the data
print(f"Data shape: {Z_tensor.shape}")

# Check the number of elements in the dataset
print(f"Number of elements: {Z_tensor.numel()}")

# Access the first few elements of the data
print("First few data elements:")
print(Z_tensor[:2])

Tensor Dataset_Z Information:
--------------------------
Data type: torch.LongTensor
Data shape: torch.Size([2555904, 1])
Number of elements: 2555904
First few data elements:
tensor([[-20],
        [-20]])


In [10]:
# Expand Z_tensor to match the dimensions of X_tensor
Z_tensor_expanded = Z_tensor.unsqueeze(-1).expand(-1, X_tensor.shape[1], X_tensor.shape[2])

In [11]:
# Concatenate X_tensor and Z_tensor_expanded along the last dimension
XZ_combined = torch.cat([X_tensor, Z_tensor_expanded], dim=2)

In [12]:
# The information about dataset XZ_combined
print("Tensor XZ_combined Information:")
print("--------------------------")

# Check the data type of the tensor dataset
print(f"Data type: {XZ_combined.type()}")

# Get the shape (dimensions) of the data
print(f"Data shape: {XZ_combined.shape}")

# Check the number of elements in the dataset
print(f"Number of elements: {XZ_combined.numel()}")

# Access the first few elements of the data
print("First few data elements:")
print(XZ_combined[:2])

Tensor XZ_combined Information:
--------------------------
Data type: torch.FloatTensor
Data shape: torch.Size([2555904, 1024, 4])
Number of elements: 10468982784
First few data elements:
tensor([[[  0.0420,   0.2348, -20.0000, -20.0000],
         [ -0.2729,   0.4051, -20.0000, -20.0000],
         [ -0.2671,   0.2275, -20.0000, -20.0000],
         ...,
         [ -0.7056,  -0.2869, -20.0000, -20.0000],
         [ -0.4116,   0.6683, -20.0000, -20.0000],
         [  0.0649,   0.6358, -20.0000, -20.0000]],

        [[  1.1986,   0.4494, -20.0000, -20.0000],
         [  0.4854,   0.2827, -20.0000, -20.0000],
         [  0.8679,  -0.3319, -20.0000, -20.0000],
         ...,
         [ -1.2129,  -0.6429, -20.0000, -20.0000],
         [ -0.3810,   0.7936, -20.0000, -20.0000],
         [  0.0864,   1.0922, -20.0000, -20.0000]]])


In [13]:
# Create an index array and use this array to reorder the two tensors
# Create index array
indices = np.arange(len(XZ_combined))
# Scramble the index
np.random.shuffle(indices)
# Reorder XZ_combined and Y_tensor using shuffled index
XZ_combined_shuffled = XZ_combined[indices]
Y_tensor_shuffled = Y_tensor[indices]

KeyboardInterrupt: 